project:
  type: website
  output-dir: docs

website:
  title: "선아"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
      - text: About
      - href: https://github.com/
      - text: Github

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



